mkswu: retry signature up to 3 times
ABOSDE's [ Generate develoment/release swu ] runs mkswu after building
the container image.
If the user fails to enter the password for signing at least once with
mkswu, the user must run [ Generate develoment/release swu ] again.

This is inconvenient as it can take time to re-build artifacts, so
allow up to three attempts to re-enter signature password.

Redmine: 63882
Change-Id: Ic98acd72f5995c978a73003ea8386d4db339c412

diff --git a/mkswu b/mkswu
--- a/mkswu
+++ b/mkswu
@@ -1674,11 +1674,19 @@ sign() {
 	[ -r "$PRIVKEY" ] || error "Cannot read PRIVKEY: %s" "$PRIVKEY"
 	[ -r "$PUBKEY" ] || error "Cannot read PUBKEY: %s" "$PUBKEY"
 
-	openssl cms -sign -in "$file" -out "$file.sig.tmp" \
-		-signer "$PUBKEY" -inkey "$PRIVKEY" \
-		-outform DER -nosmimecap -binary \
-		${PRIVKEY_PASS:+-passin "$PRIVKEY_PASS"} \
-		|| error "Could not sign %s" "$file"
+	# allow some retries for password failures
+	local retries=0
+	while ! openssl cms -sign -in "$file" -out "$file.sig.tmp" \
+			-signer "$PUBKEY" -inkey "$PRIVKEY" \
+			-outform DER -nosmimecap -binary \
+			${PRIVKEY_PASS:+-passin "$PRIVKEY_PASS"}; do
+		retries=$((retries + 1))
+		if [ -n "$PRIVKEY_PASS" ] || [ "$retries" -ge 3 ]; then
+			error "Could not sign %s" "$file"
+		fi
+		info "File signature failed, was the password correct?"
+		info "Retrying %s more time(s)." "$((3 - retries))"
+	done
 
 	mv "$file.sig.tmp" "$file.sig" \
 		|| error "Could not rename %s" "$file.sig"
