mkswu --init: add question to disable abos-web
- add examples/abosweb_set_password.desc
- add question on initial --init
- increment initial_setup.desc version and ask question
as well if older version when redoing --init

Change-Id: If3fc0659c545e371d75b7478bfd54fa870b7008f

diff --git a/mkswu b/mkswu
--- a/mkswu
+++ b/mkswu
@@ -2085,8 +2085,21 @@ geninitdesc_promptpass() {
 	PASSWD="$password"
 }
 
+geninitdesc_prompt_abosweb() {
+	local PASSWD
+
+	info "Please set the password to log into abos-web."
+	info "Not setting a password will disable the service after initial setup."
+	geninitdesc_promptpass abos-web
+	if [ "$PASSWD" != "-L" ]; then
+		sed -i -e 's:setting passwords.*:&\
+	"usermod '"$PASSWD"' abos-web-admin" \\:' "$desc.tmp" \
+			|| error "Could not update %s" "$desc.tmp"
+	fi
+}
+
 geninitdesc_fixinitdesc() {
-	local version max_version=3
+	local version max_version=4
 	version=$(sed -ne 's/.*version=\([0-9]*\).*/\1/p' "$desc")
 	if [ -z "$version" ]; then
 		echo "initial_setup.desc is too old, regenerating it"
@@ -2096,6 +2109,9 @@ geninitdesc_fixinitdesc() {
 	fi
 	[ "$version" -ge "$max_version" ] && return
 
+	trap "rm -f $desc.tmp" EXIT
+	cp "$desc" "$desc.tmp" || error "Could not copy %s to %s" "$desc" "$desc.tmp"
+
 	if [ "$version" -le 1 ]; then
 		info "atmark password was incorrectly generated, regenerating it"
 		info "if initial_setup was already installed please adjust password"
@@ -2104,29 +2120,33 @@ geninitdesc_fixinitdesc() {
 		local PASSWD
 		geninitdesc_promptpass atmark
 		sed -i -e 's:\(^[ \t]*"usermod\).*atmark:\1 '"$PASSWD"' atmark:' \
-				"$desc" \
-			|| error "Could not update %s" "$desc"
+				"$desc.tmp" \
+			|| error "Could not update %s" "$desc.tmp"
 	fi
 
 	if [ "$version" -le 2 ]; then
 		# read all to pattern space for newlines, there might be a
 		# better way of doing this but it's "good enough"
 		sed -i -e ':a;$!N;$!ba;s/\(\nswdesc_command\)\( \\\n[^\n]*usermod\)/\1 --description "setting passwords"\2/' \
-				"$desc" \
-			|| error "Could not update %s" "$desc"
+				"$desc.tmp" \
+			|| error "Could not update %s" "$desc.tmp"
+	fi
+
+	if [ "$version" -le 3 ]; then
+		geninitdesc_prompt_abosweb
 	fi
 
 	sed -i -e "s/version=[0-9]*/version=$max_version/" \
-			"$desc" \
-		|| error "Could not update %s" "$desc"
+			"$desc.tmp" \
+		|| error "Could not update %s" "$desc.tmp"
+	mv "$desc.tmp" "$desc" \
+		|| error "Could not rename %s" "$desc"
+	trap "" EXIT
 }
 
 mkinit_geninitdesc() {
-	local KEEPATMARKPEM
-	local AUTOUPDATE=""
-	local PASSWD
-	local ROOTPW
-	local ATMARKPW
+	local KEEPATMARKPEM AUTOUPDATE
+	local PASSWD ROOTPW ATMARKPW
 	local desc="$CONFIG_DIR/initial_setup.desc"
 
 	[ -e "$desc" ] && geninitdesc_fixinitdesc && return
@@ -2179,6 +2199,7 @@ swdesc_command 'rc-update add swupdate-url default' \
 	'echo -e "schedule=\"0 $AUTOUPDATE\"\nrdelay=21600" > /etc/conf.d/swupdate-url'
 EOF
 	fi
+	geninitdesc_prompt_abosweb
 
 	mv "$desc.tmp" "$desc" \
 		|| error "Could not rename %s" "$desc"
