mkswu: cpio: disable cpio built-in crc if any file is >2GB
cpio (upstream and debian bullseye versions) has a bug and does not
correctly compute its own checksum for files bigger than 2GB:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962188

Since we already compute our own checksums just disable crc if
there is any bigger file.
(Note cpio does not allow for any file bigger than 4GB either,
we might want to catch that earlier and suggest to split the
file if that ever happens...? Splitting embedded container images
might prove interesting, but that is compressed size so hopefully
should not happen)

Change-Id: I6c8c3616b6c95ef825474df30c1168d4e8b59ebc

diff --git a/mkswu b/mkswu
--- a/mkswu
+++ b/mkswu
@@ -1355,9 +1355,20 @@ mkcpio() {
 	check_common_mistakes sw-description
 	sign sw-description
 	(
+		IFS="
+"
 		cd "$OUTDIR" || error "Could not enter %s" "$OUTDIR"
-		printf %s "$FILES" | cpio -o -H crc -L --quiet
-	) > "$OUT"
+		# GNU gpio has a bug with checksums for files bigger than 2GB
+		# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962188
+		# fall back to newc in this case, we also compute sha256 for
+		# every file so this isn't a big loss
+		format=crc
+		# shellcheck disable=SC2086 # we want split by newline
+		if ! stat -L -c %s $FILES | awk '$1 > 2147483648 { exit 1; }'; then
+			format=newc
+		fi
+		printf %s "$FILES" | cpio -o -H "$format" -L --quiet
+	) > "$OUT" || error "Could not create SWU (cpio archive)"
 
 	CPIO_FILES=$(cpio -t --quiet < "$OUT")
 	[ "$CPIO_FILES" = "$FILES" ] \
