mkswu: allow running from symlink to git dir
If the user runs from a symlink we would currently resolve
the bin dir, no the symlink target.
Just use realpath + dirname

Change-Id: Ic3de969af23ca33432a34968ba4ffc82c11670f1

diff --git a/mkswu b/mkswu
--- a/mkswu
+++ b/mkswu
@@ -2325,7 +2325,9 @@ mode_to_opt() {
 
 mkimage() {
 	local SCRIPT_DIR
-	SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)" || error "Could not get script dir"
+	SCRIPT_DIR="$(realpath -- "$0")" \
+		&& SCRIPT_DIR="$(dirname -- "$SCRIPT_DIR")" \
+		|| error "Could not get script dir"
 	local OUT=""
 	local OUTDIR=""
 	local CONFIG_DIR
