improve certificate names in /etc/swupdate.pem
Instead of having all certificates named after the filename swupdate.pem,
use the CN provided by adding a comment on key creation:
- This is more descriptive as it is what they entered
- This can be matched by the user when checking their local files

This is only effective when users generate a new key, and even if the
files are edited locally only sent on initial_setup or cert update
(after generating a new key), so will not affect existing boards.

While we are here, also fix the comment in config file on extra
--genkey, we allow certificates and not keys

Change-Id: Ie56b131e38e129c70d3dfb1747ceb2f12b263873

diff --git a/mkswu b/mkswu
--- a/mkswu
+++ b/mkswu
@@ -1682,9 +1682,15 @@ mkswu_genkey_sign() {
 	info "Creating signing key %s and its public counterpart %s" "$PRIVKEY" "${PUBKEY##*/}"
 
 	openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:"$CURVE" \
-		-keyout "$PRIVKEY" -out "$PUBKEY" -subj "/O=SWUpdate/CN=$GENKEY_CN" \
+		-keyout "$PRIVKEY.tmp" -out "$PUBKEY.tmp" -subj "/O=SWUpdate/CN=$GENKEY_CN" \
 		${GENKEY_PLAIN:+-nodes} ${PRIVKEY_PASS:+-passout $PRIVKEY_PASS} \
 		-days "$DAYS" || error "Generating certificate/key pair failed"
+
+	mv "$PRIVKEY.tmp" "$PRIVKEY" \
+		|| error "Could not rename %s" "$PRIVKEY"
+	sed -e "1i# ${PUBKEY##*/}: $GENKEY_CN" "$PUBKEY.tmp" > "$PUBKEY" \
+		&& rm -f "$PUBKEY.tmp" \
+		|| error "Could not rename %s" "$PUBKEY"
 
 	if [ -n "$extrakey" ]; then
 		info "Info: Adding %s to config" "$PUBKEY"
@@ -1700,8 +1706,8 @@ mkswu_genkey_sign() {
 			|| error "Could not update %s in %s" "NEW_PRIVKEY" "$CONFIG"
 		case "$UPDATE_CERTS" in
 		[Nn]|[Nn][Oo]|[Ff][Aa][Ll][Ss][Ee]|0|"")
-			printf "%s\n" "# This controls if we should update certificates on device," \
-					"# and can be removed once all devices have been updated to only allow new key" \
+			printf "%s\n" "# This controls if we should update certificates on device, and can be" \
+					"# removed once all devices have been updated to only allow new certificate " \
 					"UPDATE_CERTS=yes" >> "$CONFIG" \
 				|| error "Could not update %s in %s" "UPDATE_CERTS" "$CONFIG"
 			;;
