scripts: make vendored scripts also use $TMPDIR/scripts-mkswu
This simplifies external scripts looking at mkswu internal state by
using the same scripts-mkswu directory for state

The drawback is that we must not remove $MKSWU_TMP when running
the pre script from SWU after the installed one was run, so
this duplicates a bit of code, but there should be no drawback
after this.

This also flags that we are using vendored scripts in a new 'vendored'
file, so post rootfs can decide to re-exec itself if required.

Change-Id: Id7c0824e270fb319688090720826f2380cf21065

diff --git a/scripts/install_boot_linux b/scripts/install_boot_linux
--- a/scripts/install_boot_linux
+++ b/scripts/install_boot_linux
@@ -57,12 +57,10 @@ write_split_boot_partition() {
 }
 
 # state variable from mkswu scripts
-if [ -e "$TMPDIR/scripts-mkswu/rootdev" ]; then
-	MKSWU_TMP="$TMPDIR/scripts-mkswu"
-elif [ -e "$TMPDIR/scripts-vendored/rootdev" ]; then
-	MKSWU_TMP="$TMPDIR/scripts-vendored"
-else
-	error "Could not find ab/rootdev in $TMPDIR/scripts or $TMPDIR/scripts-vendored, bug?"
+MKSWU_TMP="$TMPDIR/scripts-mkswu"
+
+if ! [ -e "$MKSWU_TMP/rootdev" ]; then
+	error "Could not find ab/rootdev in $MKSWU_TMP, bug?"
 fi
 ab="$(cat "$MKSWU_TMP/ab")" \
 	|| error "Could not read current partition index"
